// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Alert struct {
	ID        int64
	DeviceID  string
	Reason    string
	Desc      string
	Timestamp int64
}

type Config struct {
	DeviceID             string
	TemperatureThreshold float64
	BatteryThreshold     int64
}

type Metric struct {
	ID          int64
	DeviceID    string
	Temperature float64
	Battery     int64
	Timestamp   int64
}
