// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetDeviceAlerts(ctx context.Context, arg GetDeviceAlertsParams) ([]*Alert, error)
	GetDeviceConfig(ctx context.Context, deviceID string) (*GetDeviceConfigRow, error)
	GetDeviceMetrics(ctx context.Context, arg GetDeviceMetricsParams) ([]*Metric, error)
	SaveDeviceAlert(ctx context.Context, arg SaveDeviceAlertParams) error
	SaveDeviceMetric(ctx context.Context, arg SaveDeviceMetricParams) error
	UpsertDeviceConfig(ctx context.Context, arg UpsertDeviceConfigParams) error
}

var _ Querier = (*Queries)(nil)
